version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - roy:/app
    networks:
      - bridge-net
      - roy-net

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - roy-net

volumes:
  roy:

networks:
  bridge-net:
    driver: bridge
  roy-net:
    name: roy-net